import 'package:flutter/material.dart';

const double minimalPadding = 10;
const double minimalRadius = 8;

SizedBox separateVertical(double value) => SizedBox(height: value);
SizedBox separateHorizontal(double value) => SizedBox(width: value);

const List<String> exploreTitles = [
  "Podcasts",
  'Eventos en vivo',
  'Creados para ti',
  'Nuevos Lanzamientos',
  'Latina',
  'Pop',
  'Cumbia',
  'Música brasileña',
  'Rankings',
  'Dance/Electrónica',
  'Indie',
  'Entrenamiento',
  'Descubre',
  'Salsa',
  'Rhythm & Blues',
  'Funk de Brasil',
  'Pop coreano',
  'Para relajarse',
  'Dormir',
  'Fiesta',
  'En casa',
  'Décadas',
  'Amor',
  'Metal',
  'Jazz',
  'Tendencias',
  'Radar',
  'Anime',
  'Equal',
  'Clásica',
  'Folk & acústica',
  'Enfoque',
  'Soul',
  'Niños y familia',
  'Gaming',
  'Televisión y películas',
  'Instrumental',
  'Punk',
  'Ambient',
  'Blues',
  'Netflix',
  'Hora de la comida',
  'Alternativa',
  'Viajes',
  'Música caribeña',
  'Afro',
  'GLOW',
  'Compositores',
  'Funk',
  'Verano',
  'Country',
  'Fresh Finds',
  'Bienestar',
  'Creadores de tendencias',
  'Merch',
];

const lol = [
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
  "https://random.imagecdn.app/80/80",
];
